### ISSUE TITLE
Unable to use temporal extension methods on related models

### ISSUE THREAD

**Issue by vz28bh** [glautrou/EfCoreTemporalTable#24]
I am able to use this package successfully for single models but have not been able to figure out if it is possible to query two tables that are both temporal table. For example, the snippet below won't build 

````
var carModels = db.Cars
                .AsTemporalAll()
                .Include(c => c.CarModels)
                .AsTemporalAll()
````

`CS1061	'IIncludableQueryable<Car, ICollection<CarModel>>' does not contain a definition for 'AsTemporalAll' and no accessible extension method 'AsTemporalAll' accepting a first argument of type 'IIncludableQueryable<Car, ICollection<CarModel>>' could be found (are you missing a using directive or an assembly reference?)`

I can build the query manually and it works as expected, returned all combinations of the history records.

````
            var carModels = from car in db.Cars.AsTemporalAll()
                       join carModel in db.CarModels.AsTemporalAll() on car.CarId equals carModel.CarId
                       select new
                       {
                           Car = car,
                           CarModel = carModel
                       };
````

Is there a syntax that will support this? Thank you

**Comment by glautrou** [comment]
Unfortunately you can only do it manually.

It is important to be able to separate each table like you did because you may want an history row but with latest join data for example.

In order to support this this library should add an `IncludeTemporal` extension method which would be difficult to implement.

EF Core 6 which will be released on November 2021 should support that.
