### ISSUE TITLE
Access to date columns in history data

### ISSUE THREAD

**Issue by RedDeathGitHub** [glautrou/EfCoreTemporalTable#3]
Hi!

Really like your libarary, makes querying Temporal tables easy :).

One problem though - I want to be able to get generated date fields for current and history rows.
These would be SysStartTime and SysEndTime for the library I'm using for creating Temporal tables.
I added these properties to my entity, but when using AsTemporalAll() it throws "'The required column 'SysEndTime' was not present in the results of a 'FromSql' operation.".
When I used standard query it returned the date, but only for new (current) row obviously.

Could you please provide a sample how to query such column?

Thanks!

**Comment by glautrou** [comment]
Hi, sorry for the delay and thank you :)

Do you have some code that I can use to reproduce your issue?
I used to get this kind of issue with temporals, but that was because the [sys columns were created with an HIDDEN property](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver15#a-add-system-versioning-to-existing-tables).

**Comment by RedDeathGitHub** [comment]
No, sorry, I don't have a sample, I was messing with it a while ago.
Maybe like you said it was because of HIDDEN.

If you can create temporal table and query these columns now this should be enough to close this issue.

**Comment by glautrou** [comment]
Ok ;)
